Blog/blogs/blogs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs_first.urls')),
]

Blog/blogs/blogs_first/urls.py
"""define URLS schema for blogs_first"""

from django.urls import path

from .import views

app_name = 'blogs_first'
urlpatterns = [
    # home page
    path('', views.index, name='index'),            # page 410
    # page for new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    path('edit_blog/<int:blog_id>/', views.edit_blog, name='edit_blog'),
]

Blog/blogs/users/urls.py
"""define URLS schemas for users"""

from django import views
from django.urls import path, include
from .import views

app_name = 'users'
urlpatterns = [
    # include authorization by default
    path('', include('django.contrib.auth.urls')),
    # registration page
    path('register/', views.register, name='register'),
]

Blog/blogs/blogs_first/models.py
from django.db import models
from matplotlib.pyplot import text, title

# Create your models here.

class BlogPost(models.Model):
    """topic for blog"""
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'blogs'

    def __str__(self) -> str:
        if len(self.title) < 50:
            return f"""{self.title[:50]} {self.text[:250]}"""
        else:
            # return f"\n\t{self.title}\n"
            return f"""{self.title[:50]}... {self.text[:250]}..."""

            

Blog/blogs/users/models.py
from django.db import models

# Create your models here.

Blog/blogs/blogs_first/forms.py
from dataclasses import field, fields
from pyexpat import model
from django import forms

from .models import BlogPost

class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': '', 'text': ''}
        widgets = {'title': forms.Textarea(attrs={'cols': 35}),
            'text': forms.Textarea(attrs={'cols': 80})}

Blog/blogs/blogs_first/views.py
from django.shortcuts import render, redirect
from matplotlib.pyplot import text, title



from .models import BlogPost
from .forms import BlogForm

# Create your views here.

def index(request):
    """home page Blog"""
    blogs = BlogPost.objects.order_by('-date_added')   
    context = {'blogs': blogs, 'text': text}
    return render(request, 'blogs_first/index.html', context)

def new_topic(request):
    """define new topic"""
    if request.method != 'POST':
        # date did not send; create new form
        form = BlogForm()
    else:
        # date is sent; process date
        form = BlogForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs_first:index')
    # display empty or wrong form
    context = {'form': form}
    return render(request, 'blogs_first/new_topic.html', context)

def edit_blog(request, blog_id):
    """edit exists topic"""
    blog = BlogPost.objects.get(id=blog_id)
    
    title = blog.title
    text = blog.text

    if request.method != 'POST':
        form = BlogForm(instance=blog)
    else:
        form = BlogForm(instance=blog, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs_first:index')

    context = {'topic': blog, 'blog_id': blog.id, 'title': title, 'text': text, 'form': form}
    return render(request, 'blogs_first/edit_blog.html', context)        

Blog/blogs/users/views.py
from django.shortcuts import redirect, render
# Create your views here.
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """register a new user"""
    if request.method != 'POST':
        # displays empty form for registration
        form = UserCreationForm()
    else:
        # processing completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # log in and redirect to home page
            login(request, new_user)
            return redirect('blogs_first:index')

    # display an empty or invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)
    

Blog/blogs/blogs_first/templates/blogs_first/base.html
<p>
    <a href="{% url 'blogs_first:index' %}">Blog</a> -
    {% if user.is_authenticated %}
      Hello, {{ user.username }}.
      <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
      <a href="{% url 'users:register' %}">Register</a> - 
      <a href="{% url 'users:login' %}">log in</a>
    {% endif %}
</p>

{% block content %}{% endblock content %}

Blog/blogs/blogs_first/templates/blogs_first/edit_blog.html
{% extends 'blogs_first/base.html' %}

{% block content %}

    <p>Edit topic:</p>

    
    <form action="{% url 'blogs_first:edit_blog' blog_id %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">save changes</button>
    </form>

{% endblock content %}
   

Blog/blogs/blogs_first/templates/blogs_first/index.html
<p>{% extends 'blogs_first/base.html' %}</p>

{% block content %}
  <p>Blog helps you keep  track of news from IT.</p>

  <p>Topics</p>

  <ul>
  {% for blog in blogs %}
    <li>
        <p>{{ blog.date_added }}</p>
        <p>{{ blog.title | linebreaks }}</p>
        <p>{{ blog.text | linebreaks }}</p>
        <p>
          <a href="{% url 'blogs_first:edit_blog' blog.id %}">Edit topic</a>
        </p>
    </li>
        
  {% empty %}
    <li>No topic have been added yet.</li>
  {% endfor %}  

  </ul>

  <a href="{% url 'blogs_first:new_topic' %}">Add a new topic:</a>   

{% endblock content %}

Blog/blogs/blogs_first/templates/blogs_first/new_topic.html
{% extends 'blogs_first/base.html' %}

{% block content %}

    <p>Add a new topic:</p>

    <form action="{% url 'blogs_first:new_topic' %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">Add topic</button>
    </form>

{% endblock content %}





   