Pizzeria/pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzeria_first.urls')),
]

Pizzeria/pizzeria/pizzeria_first/urls.py
"""define URL schemes for first_pizzeria"""

from django.urls import path
from .import views

app_name = 'pizzeria_first'
urlpatterns = [
    # home page
    path('', views.index, name='index'),
    # page with list of pizzas
    path('pizzas/', views.pizzas, name='pizzas'),
    # pizza details page
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
]

Pizzeria/pizzeria/pizzeria_first/models.py
from pyexpat import model
from django.db import models
from matplotlib.pyplot import cla, text
# Create your models here.

class Pizza(models.Model):
    """types of pizza"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        """return str presentation name of pizza"""
        return self.text


class Entry(models.Model):
    """class for toppings"""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
        
    def __str__(self) -> str:
        """return str presentation of toppings"""
        if len(self.text) < 50:
            return f'{self.text[:50]}'
        else:
            return f'{self.text[:50]}...'

Pizzeria/pizzeria/pizzeria_first/views.py
from django.shortcuts import render
from .models import Pizza


# Create your views here.

def index(request):
    """home page app Pizzeria"""
    return render(request, 'pizzeria_first/index.html')

def pizzas(request):
    """display the list of pizzas"""
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas': pizzas}
    return render(request, 'pizzeria_first/pizzas.html', context)
    
def pizza(request, pizza_id):
    """display one topping and its entries"""
    pizza = Pizza.objects.get(id=pizza_id)                      # database access
    # entries = pizza.entry_set.ordered_by('-date_added')
    entries = pizza.entry_set.order_by('-date_added')   
    context = {'pizza': pizza, 'entries': entries}
    return render(request, 'pizzeria_first/pizza.html', context)

Pizzeria/pizzeria/pizzeria_first/templates/pizzeria_first/base.html
<p>
    <a href="{%  url 'pizzeria_first:index'  %}">Pizzeria Bella</a> - 
    <a href="{%  url 'pizzeria_first:pizzas' %}">Pizzas</a>
</p>
{%  block content  %}{%  endblock content  %}

Pizzeria/pizzeria/pizzeria_first/templates/pizzeria_first/index.html
{%  extends 'pizzeria_first/base.html'  %}
{%  block content  %}
  <p>Is authentic Sicilian cuisine.</p>
  <p>European quality and service.</p>
  <p>Ukrainian hospitality)))</p>
{%  endblock content  %}

Pizzeria/pizzeria/pizzeria_first/templates/pizzeria_first/pizza.html
{%  extends  'pizzeria_first/base.html'  %}

{%  block content  %}

  <p>Pizza: {{  pizza  }}</p>

  <p>Toppings:</p>
  <ul>
  {%  for entry in entries  %}
    <li>
      <!-- <p>{{  entry.date_added|date:'M d, Y H:i'  }}</p>    # display the date of topping -->
      <p>{{  entry.text | linebreaks  }}</p>
    </li>
  {%  empty  %}
    <li>There are no entries this pizza yet.</li>
  {%  endfor  %}
  </ul>
{%  endblock content %}

Pizzeria/pizzeria/pizzeria_first/templates/pizzeria_first/pizzas.html
{%  extends 'pizzeria_first/base.html'  %}

{%  block content  %}

  <p>Pizzas</p>

  <ul>
    {%  for pizza in pizzas  %}
      <li>
        <a href="{%  url 'pizzeria_first:pizza' pizza.id  %}">{{  pizza  }}</a>
      </li>
    {%  empty %}
      <li>No pizzas have been added yet.</li>
    {%  endfor  %}
  </ul>

{%  endblock content  %}  